name: Deploy

on:
    push:
        # tags:
        #     - '*'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            # - uses: shimataro/ssh-key-action@v2
            #       with:
            #           key: ${{ secrets.PRIVATE_SSH }}
            #           known_hosts: ${{ secrets.KNOWN_HOSTS }}
            #           name: id_rsa
            - run: npm install
              working-directory: ${{env.working-directory}}/website
            - run: npm run build
              working-directory: ${{env.working-directory}}/website
            - run : git config --global user.email "PaygreenBot@paygreen.fr"
            - run : git config --global user.name "PaygreenBot"
            - run : USE_SSH=true npm run deploy
              working-directory: ${{env.working-directory}}/website
