name: Deploy

on:
    push:
        tags:
            - '*'

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - run: yarn install
            - run: npm run build-storybook
            - run: npm run deploy-storybook
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
